#!/bin/bash
codebranch="master"
docbranch="gh-pages"
projectname=$(pwd | sed "s/^.*\///g")
docdirectory="Documentation"
defaultcommitmessage="Update documentation."


echo "Generating documentation for $projectname"

# stash any changes
git stash

# switch to codebranch
git checkout $codebranch

# generate the documentation in /tmp/gitappledoc/
rm -r /tmp/gitappledoc/
mkdir -p -v /tmp/gitappledoc/
appledoc --templates ~/.appledoc -p $projectname -o /tmp/gitappledoc/ "$@" ./

# if docbranch exists
if git show-ref --tags --quiet --verify -- "refs/heads/$docbranch"
then
	# switch to doc branch
	git checkout $docbranch
else 
	echo "Creating $docbranch branch"
	# create the docbranch (explained on http://pages.github.com/)
	git symbolic-ref HEAD "refs/heads/$docbranch"
	rm .git/index
	git clean -fdx
fi

# make sure stale docs are removed - re-adding will cause an update
git rm -r $docdirectory
mkdir $docdirectory

# move the generated docs to docdirectory and cleanup
mv -v /tmp/gitappledoc/html/* "$docdirectory"
rm -r /tmp/gitappledoc/

# add directory and commit with default message, allowing editing
git add -f -v "$docdirectory"
git commit -e -m "$defaultcommitmessage"

# pop the stash
git stash pop
